networks:
  minecraft-net:
    driver: bridge
  monitoring:
    driver: bridge

services:
  mc-sobrevivencia:
    image: itzg/minecraft-server
    container_name: mc-sobrevivencia
    restart: unless-stopped
    ports:
      - "25566:25565"
    volumes:
      # Dados do mundo: Usa Volume Nomeado para persistir o mundo
      - minecraft_data:/data
      # Pasta de configs (Bind Mount para a Pipeline)
      - ./paper/configs:/config
      # Plugins (Bind Mount para a Pipeline)
      - ./paper/plugins:/data/plugins

    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "10G"
      ONLINE_MODE: "false"
      VELOCITY_ENABLED: "true"
      VELOCITY_SECRET_FILE: "/config/forwarding.secret"
      VERSION: "1.21.8" # Versão fixada
    networks:
      - minecraft-net
      - monitoring
    depends_on:
      - velocity-proxy

  velocity-proxy:
    image: itzg/mc-proxy:latest
    container_name: velocity-proxy
    restart: unless-stopped
    ports:
      - "25565:25577"
    volumes:
      # configs e secret do proxy (Bind Mount para a Pipeline)
      - ./velocity:/config
      # plugins do proxy (Bind Mount para a Pipeline)
      - ./velocity/plugins:/config/plugins
    environment:
      TYPE: "VELOCITY"
      MEMORY: "1G"
    networks:
      - minecraft-net
      - monitoring

  # ==================================
  # SERVIÇOS DE MONITORAMENTO E LOGS
  # ==================================

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    restart: unless-stopped
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus # Volume Nomeado
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana # Volume Nomeado para dashboards e login
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus
      - loki
    environment:
      # CONFIGURAÇÃO SMTP para alertas de e-mail (Substituir com credenciais reais)
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: "smtp.gmail.com:587"
      GF_SMTP_USER: "SEU_EMAIL_AQUI@gmail.com"
      GF_SMTP_PASSWORD: "SUA_SENHA_DE_APP_DE_16_CARACTERES"
      GF_SMTP_FROM_ADDRESS: "SEU_EMAIL_AQUI@gmail.com"
      GF_SMTP_SKIP_VERIFY: "false"
      GF_SMTP_STARTTLS_POLICY: "VerifyStartTLS"
      GF_SMTP_FROM_NAME: "Servidor Minecraft Alertas"

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    volumes:
      - ./monitoring/loki/config.yml:/etc/loki/config.yml
      - loki_data:/data # Volume Nomeado
    ports:
      - "3100:3100"
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    user: root
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./monitoring/promtail/config.yml:/etc/promtail/config.yml
    networks:
      - monitoring
    depends_on:
      - loki

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    command:
      - "--path.rootfs=/host"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro,rslave
    ports:
      - "9100:9100"
    networks:
      - monitoring

# ==================================
# BLOCO DE DEFINIÇÃO DE VOLUMES PERSISTENTES
# Garante que dados e configs sobrevivam a DOWNs e reinícios.
# ==================================
volumes:
  minecraft_data:
  grafana_data:
  prometheus_data:
  loki_data:
