server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: container_logs
  # Removido o bloco 'filters' para garantir que o Promtail colete tudo
  docker_sd_configs:
  - host: unix:///var/run/docker.sock
    refresh_interval: 5s

  relabel_configs:
    # Captura o nome do contêiner (ex: /mc-sobrevivencia) e salva como rótulo 'container'
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'container'
      
    # Captura o nome do serviço docker-compose (ex: mc-sobrevivencia) e salva como rótulo 'compose_service'
    - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
      target_label: 'compose_service'
      
    # Captura o ID do contêiner (útil para debug)
    - source_labels: ['__meta_docker_container_id']
      target_label: 'instance'
