server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml # Onde o Promtail armazena o que já leu

clients:
  - url: http://loki:3100/loki/api/v1/push # Endereço do serviço Loki

scrape_configs:
- job_name: container_logs
  # Usa a descoberta de serviço do Docker para encontrar contêineres
  docker_sd_configs:
  - host: unix:///var/run/docker.sock
    refresh_interval: 5s
    # Filtra apenas os contêineres do Minecraft e do proxy
    filters:
      - name: container_name
        values:
          - mc-sobrevivencia
          - velocity-proxy

  relabel_configs:
    # Atribui o nome do contêiner como um rótulo no log
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'container_name'
    # Atribui o nome do serviço docker-compose como um rótulo
    - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
      target_label: 'compose_service'